<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="xunit"/>
        <PackageReference Include="xunit.runner.visualstudio"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\Aevatar.Workshop.GAgentPlugin\Aevatar.Workshop.GAgentPlugin.csproj" />
      <ProjectReference Include="..\..\src\Aevatar.Workshop.GAgent\Aevatar.Workshop.GAgent.csproj" />
      <ProjectReference Include="..\Aevatar.Workshop.TestBase\Aevatar.Workshop.TestBase.csproj" />
    </ItemGroup>

</Project>
