<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aevatar" />
        <PackageReference Include="coverlet.collector" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="Moq" />
        <PackageReference Include="xunit" />
        <PackageReference Include="xunit.runner.visualstudio" />
        <PackageReference Include="Microsoft.Extensions.Logging" />
        <PackageReference Include="Microsoft.Orleans.TestingHost" />
        <PackageReference Include="Shouldly" />
        <PackageReference Include="Volo.Abp.ObjectMapping" />
        <PackageReference Include="Volo.Abp.EventBus" />
        <PackageReference Include="Volo.Abp.Auditing" />
        <PackageReference Include="Volo.Abp.Autofac" />
        <PackageReference Include="Volo.Abp.AutoMapper" />
        <PackageReference Include="Volo.Abp.TestBase" />
        <PackageReference Include="Volo.Abp.Authorization" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\gAgents\src\Aevatar.GAgents.AIGAgent\Aevatar.GAgents.AIGAgent.csproj" />
      <ProjectReference Include="..\..\gAgents\src\Aevatar.GAgents.Executor\Aevatar.GAgents.Executor.csproj" />
      <ProjectReference Include="..\..\src\Aevatar.Workshop.GAgent\Aevatar.Workshop.GAgent.csproj" />
    </ItemGroup>

</Project>
