import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  "quick-start": [
    {
      type: "doc",
      id: "quick-start/index",
      label: "Quick Start"
    }
  ],

  "document": [
    {
      type: "category",
      label: "Document",
      collapsible: false,
      link: {
        type: "generated-index",
        slug: "/document",
      },
      items: [
        { type: "doc", id: "document/overview", label: "Overview" },
        { type: "doc", id: "document/gagent", label: "GAgent" },
        { type: "doc", id: "document/event-handlers", label: "Event Handlers" },
        { type: "doc", id: "document/gagent-attribute", label: "GAgent Attribute" },
        { type: "doc", id: "document/gagent-factory", label: "GAgentFactory" },
        { type: "doc", id: "document/gagent-mongodb-event-sourcing", label: "GAgent EventSourcing" },
        { type: "doc", id: "document/aevatar-signalR", label: "Aevatar SignalR" }
      ],
    },
  ],
  
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
