<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aevatar.Core.Abstractions"/>
        <PackageReference Include="Aevatar.Core"/>
        <PackageReference Include="Aevatar.EventSourcing.Core"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\gAgents\src\Aevatar.GAgents.AI.Abstractions\Aevatar.GAgents.AI.Abstractions.csproj" />
      <ProjectReference Include="..\..\gAgents\src\Aevatar.GAgents.AIGAgent\Aevatar.GAgents.AIGAgent.csproj" />
      <ProjectReference Include="..\..\gAgents\src\Aevatar.GAgents.Basic\Aevatar.GAgents.Basic.csproj" />
    </ItemGroup>

</Project>
