<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup Condition="'$(UseLocalProjects)' != 'true'">
        <PackageReference Include="Aevatar.Core.Abstractions"/>
        <PackageReference Include="Aevatar.Core"/>
        <PackageReference Include="Aevatar.EventSourcing.Core"/>
        <PackageReference Include="Aevatar.GAgents.AI.Abstractions" />
        <PackageReference Include="Aevatar.GAgents.AIGAgent" />
        <PackageReference Include="Aevatar.GAgents.Basic" />
        <PackageReference Include="Aevatar.GAgents.Executor" />
        <PackageReference Include="Aevatar.GAgents.PsiOmni" />
        <PackageReference Include="Aevatar.GAgents.GroupChat" />
    </ItemGroup>

    <ItemGroup Condition="'$(UseLocalProjects)' == 'true'">
        <ProjectReference Include="..\..\..\aevatar-station\framework\src\Aevatar.Core.Abstractions\Aevatar.Core.Abstractions.csproj" />
        <ProjectReference Include="..\..\..\aevatar-station\framework\src\Aevatar.Core\Aevatar.Core.csproj" />
        <ProjectReference Include="..\..\..\aevatar-station\framework\src\Aevatar.EventSourcing.Core\Aevatar.EventSourcing.Core.csproj" />
        <ProjectReference Include="..\..\..\aevatar-gagents\src\Aevatar.GAgents.AI.Abstractions\Aevatar.GAgents.AI.Abstractions.csproj" />
        <ProjectReference Include="..\..\..\aevatar-gagents\src\Aevatar.GAgents.AIGAgent\Aevatar.GAgents.AIGAgent.csproj" />
        <ProjectReference Include="..\..\..\aevatar-gagents\src\Aevatar.GAgents.Basic\Aevatar.GAgents.Basic.csproj" />
        <ProjectReference Include="..\..\..\aevatar-gagents\src\Aevatar.GAgents.Executor\Aevatar.GAgents.Executor.csproj" />
        <ProjectReference Include="..\..\..\aevatar-gagents\src\Aevatar.GAgents.PsiOmni\Aevatar.GAgents.PsiOmni.csproj" />
        <ProjectReference Include="..\..\..\aevatar-gagents\src\Aevatar.GAgents.GroupChat\Aevatar.GAgents.GroupChat.csproj" />
    </ItemGroup>

</Project>
