<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aevatar.Core.Abstractions"/>
        <PackageReference Include="Aevatar.Core"/>
        <PackageReference Include="Aevatar.EventSourcing.Core"/>
        <PackageReference Include="Aevatar.GAgents.AI.Abstractions" />
        <PackageReference Include="Aevatar.GAgents.AIGAgent" />
        <PackageReference Include="Aevatar.GAgents.Basic" />
    </ItemGroup>

</Project>
